---
exclude:
  - "**/vendor/bundle/**"
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # Suggested by https://github.com/Shopify/erb-lint#rubocop
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
  ErbSafety:
    enabled: false
  PartialInstanceVariable:
    enabled: false
  DeprecatedClasses:
    enabled: true
  NoUnusedDisable:
    enabled: true
  RubocopText:
    enabled: true
