inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/bundle
    - db/migrate/**
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*
    - tmp/**/*
    - log/**/*
    - fedora_conf/**/*
    - public/**/*
    - coverage/**/*
    - postgres-data/**/*
    - spec/fixtures/**/*

Rails:
  Enabled: true

# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Max: 180
  IgnoredPatterns:
    - '\A\s*#' # allow long comments

# Offense count: 166
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 25
  ExcludedMethods:
    - 'configure_blacklight'
    - 'Dor.configure'
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'lib/tasks/*.rake'
    - 'app/jobs/create_virtual_objects_job.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true