require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - bin/**
    - vendor/bundle/**/*

inherit_from:
  - .rubocop_todo.yml
