inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - standard-rails
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

inherit_from:
  - .rubocop/custom.yml
  - .rubocop_todo.yml

# Where are all the new RSpec/Capybara/FactoryBot cops? .rubocop/custom.yml
