inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**
    - db/migrate/**
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*
    - tmp/**/*
    - log/**/*
    - fedora_conf/**/*
    - public/**/*
    - coverage/**/*
    - postgres-data/**/*
    - spec/fixtures/**/*

Rails:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# Offense count: 166
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 25
  ExcludedMethods:
    - 'configure_blacklight'
    - 'Dor.configure'
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'lib/**/*.rake'
    - 'app/jobs/create_virtual_objects_job.rb'

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

RSpec/MultipleExpectations:
  Enabled: false

Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true

Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true

Lint/EmptyFile: # (new in 0.90)
  Enabled: true

Lint/IdentityComparison: # (new in 0.91)
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true

Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true

Lint/UselessTimes: # (new in 0.91)
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - 'app/components/**/*'
    - 'config/initializers/okcomputer.rb'

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CombinableLoops: # (new in 0.90)
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot: # (new in 2.8)
  Enabled: true
