source :rubygems
source 'http://sul-gems.stanford.edu'

group :deployment do
  gem 'json'
	gem 'capistrano'
  gem 'capistrano-ext'
  gem 'rvm-capistrano'
  gem 'lyberteam-devel', '>=1.0.0'
  gem 'lyberteam-gems-devel', '>=1.0.0'
  gem 'net-ssh-kerberos'
end
