bulk_metadata:
  directory: 'spec/fixtures/bulk_upload/workspace/'

# URLs
solrizer_url: 'http://localhost:8983/solr/argo'
dor_indexing_url: http://localhost:3004/dor

features:
  ocr_workflow: true
  speech_to_text_workflow: true
