bulk_metadata:
  directory: 'spec/fixtures/bulk_upload/workspace/'

# URLs
fedora_url:   'http://fedoraAdmin:fedoraAdmin@localhost:8983/fedora'
solrizer_url: 'http://localhost:8984/solr/argo'
dor_indexing_url: http://localhost:3004/dor
