require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BulkActionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BulkAction. As you add validations to BulkAction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BulkActionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bulk_actions as @bulk_actions" do
      bulk_action = BulkAction.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bulk_actions)).to eq([bulk_action])
    end
  end

  describe "GET #show" do
    it "assigns the requested bulk_action as @bulk_action" do
      bulk_action = BulkAction.create! valid_attributes
      get :show, {:id => bulk_action.to_param}, valid_session
      expect(assigns(:bulk_action)).to eq(bulk_action)
    end
  end

  describe "GET #new" do
    it "assigns a new bulk_action as @bulk_action" do
      get :new, {}, valid_session
      expect(assigns(:bulk_action)).to be_a_new(BulkAction)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bulk_action as @bulk_action" do
      bulk_action = BulkAction.create! valid_attributes
      get :edit, {:id => bulk_action.to_param}, valid_session
      expect(assigns(:bulk_action)).to eq(bulk_action)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BulkAction" do
        expect {
          post :create, {:bulk_action => valid_attributes}, valid_session
        }.to change(BulkAction, :count).by(1)
      end

      it "assigns a newly created bulk_action as @bulk_action" do
        post :create, {:bulk_action => valid_attributes}, valid_session
        expect(assigns(:bulk_action)).to be_a(BulkAction)
        expect(assigns(:bulk_action)).to be_persisted
      end

      it "redirects to the created bulk_action" do
        post :create, {:bulk_action => valid_attributes}, valid_session
        expect(response).to redirect_to(BulkAction.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bulk_action as @bulk_action" do
        post :create, {:bulk_action => invalid_attributes}, valid_session
        expect(assigns(:bulk_action)).to be_a_new(BulkAction)
      end

      it "re-renders the 'new' template" do
        post :create, {:bulk_action => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bulk_action" do
        bulk_action = BulkAction.create! valid_attributes
        put :update, {:id => bulk_action.to_param, :bulk_action => new_attributes}, valid_session
        bulk_action.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bulk_action as @bulk_action" do
        bulk_action = BulkAction.create! valid_attributes
        put :update, {:id => bulk_action.to_param, :bulk_action => valid_attributes}, valid_session
        expect(assigns(:bulk_action)).to eq(bulk_action)
      end

      it "redirects to the bulk_action" do
        bulk_action = BulkAction.create! valid_attributes
        put :update, {:id => bulk_action.to_param, :bulk_action => valid_attributes}, valid_session
        expect(response).to redirect_to(bulk_action)
      end
    end

    context "with invalid params" do
      it "assigns the bulk_action as @bulk_action" do
        bulk_action = BulkAction.create! valid_attributes
        put :update, {:id => bulk_action.to_param, :bulk_action => invalid_attributes}, valid_session
        expect(assigns(:bulk_action)).to eq(bulk_action)
      end

      it "re-renders the 'edit' template" do
        bulk_action = BulkAction.create! valid_attributes
        put :update, {:id => bulk_action.to_param, :bulk_action => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bulk_action" do
      bulk_action = BulkAction.create! valid_attributes
      expect {
        delete :destroy, {:id => bulk_action.to_param}, valid_session
      }.to change(BulkAction, :count).by(-1)
    end

    it "redirects to the bulk_actions list" do
      bulk_action = BulkAction.create! valid_attributes
      delete :destroy, {:id => bulk_action.to_param}, valid_session
      expect(response).to redirect_to(bulk_actions_url)
    end
  end

end
